import random
import turtle
t = turtle.Pen()
t.hideturtle()
t.speed(0)
turtle.bgcolor("black")
def smiley(x,y):
    t.setpos(x,y)
    t.pencolor("yellow")
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.setpos(x-15, y+60)
    t.pencolor("black")
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.setpos(x+15, y+60)
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.setpos(x-25, y+40)
    t.pencolor("black")
    t.fillcolor("black")
    t.width(10)
    t.goto(x-10, y+20)
    t.goto(x+10, y+20)
    t.goto(x+25, y+40)
    t.width(1)
turtle.onscreenclick(smiley)
turtle.done()
