import random
import turtle
t = turtle.Pen()
t.speed(0)
t.hideturtle()
turtle.bgcolor("black")
def smiley(x,y):
    t.penup()
    t.setpos(x,y)
    t.pendown()
    t.pencolor("yellow")
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.setpos(x-15, y+60)
    t.pencolor("black")
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.setpos(x+15, y+60)
    t.pendown()
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.setpos(x-25, y+40)
    t.pendown()
    t.pencolor("black")
    t.fillcolor("black")
    t.width(10)
    t.goto(x-10, y+20)
    t.goto(x+10, y+20)
    t.goto(x+25, y+40)
    t.width(1)
for n in range(50):
    x = random.randrange(-turtle.window_width()//2,
                         turtle.window_width()//2)
    y = random.randrange(-turtle.window_height()//2,
                         turtle.window_height()//2)
    smiley(x,y)
turtle.done()
